Repository tarkowr/Tic_Tac_Toe_v2_Barsheff_Miller_Tarkowski, pull requests merged in 2018-09, with the labels that each got.

#4 fixed bug if player won
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleView.cs
Labels: bug

#5 Configure model
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/Gameboard.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleView.cs
Labels: enhancement

#8 added two manage methods for the two menus
  .gitignore
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/MenuOption.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleView.cs
Labels: enhancement

#10 Cats Game Check
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/Gameboard.cs
Labels: cleanup, enhancement

#11 Exit round functionality
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
Labels: enhancement

#12 Disable user prompt
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
Labels: cleanup, documentation, enhancement

#13 Feature/win
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/Gameboard.cs
Labels: enhancement

#14 Feature/model
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/Gameboard.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleView.cs
Labels: enhancement

#21 added xml documentation and cleaned up code
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/Gameboard.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/GameboardPosition.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/MenuOption.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Utilities/ConsoleUtil.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleConfig.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleView.cs
Labels: cleanup, documentation

#23 Added Sound class
  CodingActivity_TicTacToe_ConsoleGame.Solution/CodingActivity_TicTacToe_ConsoleGame.Solution.csproj
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/Sound.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleView.cs
Labels: enhancement

#27 Added Help Feature
  CodingActivity_TicTacToe_ConsoleGame.Solution/Controller/Controller.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/Model/Gameboard.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/View/ConsoleView.cs
  CodingActivity_TicTacToe_ConsoleGame.Solution/bin/Debug/CodingActivity_TicTacToe_ConsoleGame.exe
Labels: enhancement
